Report Layout/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Report_Layout.Models;

namespace Report_Layout.Controllers
{
    public class ReportController : Controller
    {
        
        DBManager db = new DBManager();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DetailReport()
        {
            var detail = db.GetDetailReport();
            return View(detail);
        }
        [HttpGet]
        public ActionResult ExceptionReport()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ExceptionReport(FormCollection collection)
        {
            string val = collection["ExceptionValue"];
            Except type = (Except)Enum.Parse(typeof(Except), collection["ExceptionType"]);
            Inequality ineq = (Inequality)Enum.Parse(typeof(Inequality), collection["EqualityType"]);

            ViewBag.date = true;
            var execption = db.GetExceptionReport(type, ineq, val);
            TempData["val"] = val;
            TempData["type"] = type;
            TempData["ineq"] = ineq;
            return View("ExceptionReportList", execption);
        }

        public ActionResult ExceptionReportList()
        {
            return View();
        }
        public ActionResult SummaryReport()
        {
            var summary = db.GetSummaryReport();
            return View(summary);
        }
    }
}

Report Layout/Controllers/TripController.cs
using Report_Layout.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Report_Layout.Controllers
{
    public class TripController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {

            // new trip class object 
            Trip trip = new Trip();

            // Retrieve data from Form 

            trip.TruckNumber = collection["truckNum"];

            trip.DriverNumber = collection["driverNum"];

            trip.CoDriverNumber = collection["co-driverNum"];

            trip.TripNumber = collection["tripNum"];

            trip.DateDeparted = Convert.ToDateTime(collection["dateDeparted"]);

            trip.DateReturned = Convert.ToDateTime(collection["dateReturn"]);

            trip.StateCode = collection["state"];

            trip.MilesDriven = Convert.ToInt32(collection["milesDriven"]);

            trip.ReceiptNumber = collection["receiptNum"];

            trip.GallonsPurchased = Convert.ToDouble(collection["gallonsPurchased"]);

            trip.TaxesPaid = Convert.ToDouble(collection["taxesPaid"]);

            trip.StationName = collection["stationName"];

            trip.Location = collection["stationLocation"];


            // Manipulation 
            Database.tripList.Add(trip);

            // Return Report? 
            //  ViewBag or Session? 

            //Session["trip"] = trip;

            // retreieve the trip class object in report or elsewhere 


            return RedirectToAction("Success");
        }

        public ActionResult Success()
        {
            return View();
        }
    }
}

Report Layout/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Trip Journal", "Index", "Trip", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Trip Reports", "Index", "Report", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <footer>
            
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>